// MLB matchup data — auto-generated by update.py on 2026-08-02 09:54.
// Scores are recomputed live in the browser from these inputs + the weights below.
window.SLATE = {
  date: "2026-08-02",
  scales: {
    xERA:    { min: 2.5,   max: 6.5,  higherIsBetter: true },
    bullpen: { min: 2.5,   max: 6.5,  higherIsBetter: true },
    ops:     { min: 0.625, max: 0.8,  higherIsBetter: true },
    opsL3:   { min: 0.5,   max: 0.9,  higherIsBetter: true },
    runsL3:  { min: 2,     max: 8,    higherIsBetter: true }
  },
  weights: { xERA: 0.24, ops: 0.19, bullpen: 0.25, runsL3: 0.00, opsL3: 0.32 },
  rows: [
    { game:"PHI @ BAL", team:"Philadelphia Phillies", abbr:"PHI", ha:"Away", pitcher:"Zack Wheeler", opp:"Baltimore Orioles", oppPitcher:"Kyle Bradish", oppId:680694, oppXERA:3.99, oppBullpenERA:4.03, bullpenSO:39.89, runsL3:null, ops:null, opsL3:null },
    { game:"PHI @ BAL", team:"Baltimore Orioles", abbr:"BAL", ha:"Home", pitcher:"Kyle Bradish", opp:"Philadelphia Phillies", oppPitcher:"Zack Wheeler", oppId:554430, oppXERA:2.65, oppBullpenERA:4.43, bullpenSO:34.26, runsL3:null, ops:null, opsL3:null },
    { game:"WSH @ ATL", team:"Washington Nationals", abbr:"WSH", ha:"Away", pitcher:"Cade Cavalli", opp:"Atlanta Braves", oppPitcher:"JR Ritchie", oppId:702275, oppXERA:4.8, oppBullpenERA:3.46, bullpenSO:37.1, runsL3:null, ops:null, opsL3:null },
    { game:"WSH @ ATL", team:"Atlanta Braves", abbr:"ATL", ha:"Home", pitcher:"JR Ritchie", opp:"Washington Nationals", oppPitcher:"Cade Cavalli", oppId:676917, oppXERA:4.02, oppBullpenERA:4.96, bullpenSO:55.13, runsL3:null, ops:null, opsL3:null },
    { game:"STL @ TOR", team:"St. Louis Cardinals", abbr:"STL", ha:"Away", pitcher:"Matthew Liberatore", opp:"Toronto Blue Jays", oppPitcher:"Max Scherzer", oppId:453286, oppXERA:6.12, oppBullpenERA:3.82, bullpenSO:39.25, runsL3:null, ops:null, opsL3:null },
    { game:"STL @ TOR", team:"Toronto Blue Jays", abbr:"TOR", ha:"Home", pitcher:"Max Scherzer", opp:"St. Louis Cardinals", oppPitcher:"Matthew Liberatore", oppId:669461, oppXERA:5.13, oppBullpenERA:4.37, bullpenSO:52.6, runsL3:null, ops:null, opsL3:null },
    { game:"ARI @ CLE", team:"Arizona Diamondbacks", abbr:"ARI", ha:"Away", pitcher:"Merrill Kelly", opp:"Cleveland Guardians", oppPitcher:"Gavin Williams", oppId:668909, oppXERA:3.99, oppBullpenERA:3.91, bullpenSO:37.29, runsL3:null, ops:null, opsL3:null },
    { game:"ARI @ CLE", team:"Cleveland Guardians", abbr:"CLE", ha:"Home", pitcher:"Gavin Williams", opp:"Arizona Diamondbacks", oppPitcher:"Merrill Kelly", oppId:518876, oppXERA:7.13, oppBullpenERA:4.2, bullpenSO:39.57, runsL3:null, ops:null, opsL3:null },
    { game:"PIT @ CIN", team:"Pittsburgh Pirates", abbr:"PIT", ha:"Away", pitcher:"Mitch Keller", opp:"Cincinnati Reds", oppPitcher:"Chase Burns", oppId:695505, oppXERA:3.19, oppBullpenERA:4.5, bullpenSO:61.68, runsL3:null, ops:null, opsL3:null },
    { game:"PIT @ CIN", team:"Cincinnati Reds", abbr:"CIN", ha:"Home", pitcher:"Chase Burns", opp:"Pittsburgh Pirates", oppPitcher:"Mitch Keller", oppId:656605, oppXERA:5.1, oppBullpenERA:4.34, bullpenSO:46.52, runsL3:null, ops:null, opsL3:null },
    { game:"CHW @ TB", team:"Chicago White Sox", abbr:"CHW", ha:"Away", pitcher:"Anthony Kay", opp:"Tampa Bay Rays", oppPitcher:"Griffin Jax", oppId:643377, oppXERA:4.71, oppBullpenERA:3.93, bullpenSO:37.59, runsL3:null, ops:null, opsL3:null },
    { game:"CHW @ TB", team:"Tampa Bay Rays", abbr:"TB", ha:"Home", pitcher:"Griffin Jax", opp:"Chicago White Sox", oppPitcher:"Anthony Kay", oppId:641743, oppXERA:5.13, oppBullpenERA:3.79, bullpenSO:46.63, runsL3:null, ops:null, opsL3:null },
    { game:"MIA @ NYM", team:"Miami Marlins", abbr:"MIA", ha:"Away", pitcher:"Sandy Alcantara", opp:"New York Mets", oppPitcher:"Robert Stock", oppId:476594, oppXERA:null, oppBullpenERA:3.82, bullpenSO:35.91, runsL3:null, ops:null, opsL3:null },
    { game:"MIA @ NYM", team:"New York Mets", abbr:"NYM", ha:"Home", pitcher:"Robert Stock", opp:"Miami Marlins", oppPitcher:"Sandy Alcantara", oppId:645261, oppXERA:3.77, oppBullpenERA:3.89, bullpenSO:42.28, runsL3:null, ops:null, opsL3:null },
    { game:"TEX @ HOU", team:"Texas Rangers", abbr:"TEX", ha:"Away", pitcher:"Kumar Rocker", opp:"Houston Astros", oppPitcher:"Peter Lambert", oppId:663567, oppXERA:3.43, oppBullpenERA:4.11, bullpenSO:44.32, runsL3:null, ops:null, opsL3:null },
    { game:"TEX @ HOU", team:"Houston Astros", abbr:"HOU", ha:"Home", pitcher:"Peter Lambert", opp:"Texas Rangers", oppPitcher:"Kumar Rocker", oppId:677958, oppXERA:4.58, oppBullpenERA:4.26, bullpenSO:40.88, runsL3:null, ops:null, opsL3:null },
    { game:"NYY @ CHC", team:"New York Yankees", abbr:"NYY", ha:"Away", pitcher:"Gerrit Cole", opp:"Chicago Cubs", oppPitcher:"Colin Rea", oppId:607067, oppXERA:5.52, oppBullpenERA:3.91, bullpenSO:42.67, runsL3:null, ops:null, opsL3:null },
    { game:"NYY @ CHC", team:"Chicago Cubs", abbr:"CHC", ha:"Home", pitcher:"Colin Rea", opp:"New York Yankees", oppPitcher:"Gerrit Cole", oppId:543037, oppXERA:3.28, oppBullpenERA:3.03, bullpenSO:41.02, runsL3:null, ops:null, opsL3:null },
    { game:"KC @ COL", team:"Kansas City Royals", abbr:"KC", ha:"Away", pitcher:"Seth Lugo", opp:"Colorado Rockies", oppPitcher:"Kyle Freeland", oppId:607536, oppXERA:5.63, oppBullpenERA:4.97, bullpenSO:46.72, runsL3:null, ops:null, opsL3:null },
    { game:"KC @ COL", team:"Colorado Rockies", abbr:"COL", ha:"Home", pitcher:"Kyle Freeland", opp:"Kansas City Royals", oppPitcher:"Seth Lugo", oppId:607625, oppXERA:5.38, oppBullpenERA:5.37, bullpenSO:59.05, runsL3:null, ops:null, opsL3:null },
    { game:"MIL @ LAA", team:"Milwaukee Brewers", abbr:"MIL", ha:"Away", pitcher:"Jacob Misiorowski", opp:"Los Angeles Angels", oppPitcher:"Walbert Ureña", oppId:700712, oppXERA:3.26, oppBullpenERA:4.37, bullpenSO:46.49, runsL3:null, ops:null, opsL3:null },
    { game:"MIL @ LAA", team:"Los Angeles Angels", abbr:"LAA", ha:"Home", pitcher:"Walbert Ureña", opp:"Milwaukee Brewers", oppPitcher:"Jacob Misiorowski", oppId:694819, oppXERA:1.96, oppBullpenERA:3.62, bullpenSO:41.11, runsL3:null, ops:null, opsL3:null },
    { game:"DET @ ATH", team:"Detroit Tigers", abbr:"DET", ha:"Away", pitcher:"Keider Montero", opp:"Athletics", oppPitcher:"Gage Jump", oppId:695611, oppXERA:4.07, oppBullpenERA:5.64, bullpenSO:45.15, runsL3:null, ops:null, opsL3:null },
    { game:"DET @ ATH", team:"Athletics", abbr:"ATH", ha:"Home", pitcher:"Gage Jump", opp:"Detroit Tigers", oppPitcher:"Keider Montero", oppId:672456, oppXERA:3.48, oppBullpenERA:3.86, bullpenSO:44.68, runsL3:null, ops:null, opsL3:null },
    { game:"SF @ SD", team:"San Francisco Giants", abbr:"SF", ha:"Away", pitcher:"Landen Roupp", opp:"San Diego Padres", oppPitcher:"Michael King", oppId:650633, oppXERA:4.58, oppBullpenERA:3.62, bullpenSO:37.14, runsL3:null, ops:null, opsL3:null },
    { game:"SF @ SD", team:"San Diego Padres", abbr:"SD", ha:"Home", pitcher:"Michael King", opp:"San Francisco Giants", oppPitcher:"Landen Roupp", oppId:694738, oppXERA:3.48, oppBullpenERA:4.29, bullpenSO:54.91, runsL3:null, ops:null, opsL3:null },
    { game:"MIN @ SEA", team:"Minnesota Twins", abbr:"MIN", ha:"Away", pitcher:"Taj Bradley", opp:"Seattle Mariners", oppPitcher:"George Kirby", oppId:669923, oppXERA:3.91, oppBullpenERA:3.52, bullpenSO:37.76, runsL3:null, ops:null, opsL3:null },
    { game:"MIN @ SEA", team:"Seattle Mariners", abbr:"SEA", ha:"Home", pitcher:"George Kirby", opp:"Minnesota Twins", oppPitcher:"Taj Bradley", oppId:671737, oppXERA:3.82, oppBullpenERA:4.85, bullpenSO:57.14, runsL3:null, ops:null, opsL3:null },
    { game:"BOS @ LAD", team:"Boston Red Sox", abbr:"BOS", ha:"Away", pitcher:"Jake Bennett", opp:"Los Angeles Dodgers", oppPitcher:"Emmet Sheehan", oppId:686218, oppXERA:3.77, oppBullpenERA:4.01, bullpenSO:42.09, runsL3:null, ops:null, opsL3:null },
    { game:"BOS @ LAD", team:"Los Angeles Dodgers", abbr:"LAD", ha:"Home", pitcher:"Emmet Sheehan", opp:"Boston Red Sox", oppPitcher:"Jake Bennett", oppId:687562, oppXERA:3.07, oppBullpenERA:2.95, bullpenSO:33.25, runsL3:null, ops:null, opsL3:null }
  ],
  runsRank: [],
  opsRank: [],
  bullpen: [["ATH", 5.64, 1.51, 200, 443, 45.15], ["KC", 5.37, 1.56, 199, 337, 59.05], ["COL", 4.97, 1.49, 185, 396, 46.72], ["WSH", 4.96, 1.47, 231, 419, 55.13], ["MIN", 4.85, 1.51, 212, 371, 57.14], ["CIN", 4.5, 1.45, 235, 381, 61.68], ["PHI", 4.43, 1.34, 148, 432, 34.26], ["LAA", 4.37, 1.38, 212, 456, 46.49], ["STL", 4.37, 1.39, 192, 365, 52.6], ["PIT", 4.34, 1.41, 214, 460, 46.52], ["SF", 4.29, 1.41, 179, 326, 54.91], ["TEX", 4.26, 1.33, 139, 340, 40.88], ["ARI", 4.2, 1.24, 129, 326, 39.57], ["HOU", 4.11, 1.3, 199, 449, 44.32], ["BAL", 4.03, 1.27, 146, 366, 39.89], ["LAD", 4.01, 1.27, 165, 392, 42.09], ["TB", 3.93, 1.19, 153, 407, 37.59], ["CHC", 3.91, 1.31, 160, 375, 42.67], ["CLE", 3.91, 1.32, 157, 421, 37.29], ["MIA", 3.89, 1.21, 178, 421, 42.28], ["DET", 3.86, 1.32, 172, 385, 44.68], ["NYM", 3.82, 1.24, 167, 465, 35.91], ["TOR", 3.82, 1.3, 179, 456, 39.25], ["CHW", 3.79, 1.3, 228, 489, 46.63], ["SD", 3.62, 1.26, 179, 482, 37.14], ["MIL", 3.62, 1.28, 178, 433, 41.11], ["SEA", 3.52, 1.27, 128, 339, 37.76], ["ATL", 3.46, 1.18, 151, 407, 37.1], ["NYY", 3.03, 1.21, 153, 373, 41.02], ["BOS", 2.95, 1.15, 130, 391, 33.25]]
};
