// MLB matchup data — auto-generated by update.py on 2026-08-01 16:04.
// Scores are recomputed live in the browser from these inputs + the weights below.
window.SLATE = {
  date: "2026-08-01",
  scales: {
    xERA:    { min: 2.5,   max: 6.5,  higherIsBetter: true },
    bullpen: { min: 2.5,   max: 6.5,  higherIsBetter: true },
    ops:     { min: 0.625, max: 0.8,  higherIsBetter: true },
    opsL3:   { min: 0.5,   max: 0.9,  higherIsBetter: true },
    runsL3:  { min: 2,     max: 8,    higherIsBetter: true }
  },
  weights: { xERA: 0.24, ops: 0.19, bullpen: 0.25, runsL3: 0.00, opsL3: 0.32 },
  rows: [
    { game:"STL @ TOR", team:"St. Louis Cardinals", abbr:"STL", ha:"Away", pitcher:"Quinn Mathews", opp:"Toronto Blue Jays", oppPitcher:"Kevin Gausman", oppId:592332, oppXERA:3.93, oppBullpenERA:3.84, bullpenSO:38.99, runsL3:null, ops:null, opsL3:null },
    { game:"STL @ TOR", team:"Toronto Blue Jays", abbr:"TOR", ha:"Home", pitcher:"Kevin Gausman", opp:"St. Louis Cardinals", oppPitcher:"Quinn Mathews", oppId:687273, oppXERA:null, oppBullpenERA:4.33, bullpenSO:52.47, runsL3:null, ops:null, opsL3:null },
    { game:"MIN @ SEA", team:"Minnesota Twins", abbr:"MIN", ha:"Away", pitcher:"Connor Prielipp", opp:"Seattle Mariners", oppPitcher:"Logan Gilbert", oppId:669302, oppXERA:3.64, oppBullpenERA:3.54, bullpenSO:37.8, runsL3:null, ops:null, opsL3:null },
    { game:"MIN @ SEA", team:"Seattle Mariners", abbr:"SEA", ha:"Home", pitcher:"Logan Gilbert", opp:"Minnesota Twins", oppPitcher:"Connor Prielipp", oppId:687570, oppXERA:4.05, oppBullpenERA:4.87, bullpenSO:56.52, runsL3:null, ops:null, opsL3:null },
    { game:"CHW @ TB", team:"Chicago White Sox", abbr:"CHW", ha:"Away", pitcher:"Jordan Hicks", opp:"Tampa Bay Rays", oppPitcher:"Drew Rasmussen", oppId:656876, oppXERA:3.12, oppBullpenERA:3.96, bullpenSO:38.15, runsL3:null, ops:null, opsL3:null },
    { game:"CHW @ TB", team:"Tampa Bay Rays", abbr:"TB", ha:"Home", pitcher:"Drew Rasmussen", opp:"Chicago White Sox", oppPitcher:"Jordan Hicks", oppId:663855, oppXERA:3.09, oppBullpenERA:3.82, bullpenSO:47.3, runsL3:null, ops:null, opsL3:null },
    { game:"MIA @ NYM", team:"Miami Marlins", abbr:"MIA", ha:"Away", pitcher:"Tyler Phillips", opp:"New York Mets", oppPitcher:"Zac Thornton", oppId:804267, oppXERA:4.55, oppBullpenERA:3.82, bullpenSO:35.79, runsL3:null, ops:null, opsL3:null },
    { game:"MIA @ NYM", team:"New York Mets", abbr:"NYM", ha:"Home", pitcher:"Zac Thornton", opp:"Miami Marlins", oppPitcher:"Tyler Phillips", oppId:663969, oppXERA:4.71, oppBullpenERA:3.92, bullpenSO:42.48, runsL3:null, ops:null, opsL3:null },
    { game:"PIT @ CIN", team:"Pittsburgh Pirates", abbr:"PIT", ha:"Away", pitcher:"Braxton Ashcraft", opp:"Cincinnati Reds", oppPitcher:"Andrew Abbott", oppId:671096, oppXERA:4.74, oppBullpenERA:4.52, bullpenSO:61.48, runsL3:null, ops:null, opsL3:null },
    { game:"PIT @ CIN", team:"Cincinnati Reds", abbr:"CIN", ha:"Home", pitcher:"Andrew Abbott", opp:"Pittsburgh Pirates", oppPitcher:"Braxton Ashcraft", oppId:677952, oppXERA:3.48, oppBullpenERA:4.38, bullpenSO:46.81, runsL3:null, ops:null, opsL3:null },
    { game:"PHI @ BAL", team:"Philadelphia Phillies", abbr:"PHI", ha:"Away", pitcher:"Cristopher Sánchez", opp:"Baltimore Orioles", oppPitcher:"Shane Baz", oppId:669358, oppXERA:4.31, oppBullpenERA:3.96, bullpenSO:39.39, runsL3:null, ops:null, opsL3:null },
    { game:"PHI @ BAL", team:"Baltimore Orioles", abbr:"BAL", ha:"Home", pitcher:"Shane Baz", opp:"Philadelphia Phillies", oppPitcher:"Cristopher Sánchez", oppId:650911, oppXERA:3.36, oppBullpenERA:4.47, bullpenSO:34.5, runsL3:null, ops:null, opsL3:null },
    { game:"TEX @ HOU", team:"Texas Rangers", abbr:"TEX", ha:"Away", pitcher:"Jacob deGrom", opp:"Houston Astros", oppPitcher:"Ronel Blanco", oppId:669854, oppXERA:6.78, oppBullpenERA:4.13, bullpenSO:44.47, runsL3:null, ops:null, opsL3:null },
    { game:"TEX @ HOU", team:"Houston Astros", abbr:"HOU", ha:"Home", pitcher:"Ronel Blanco", opp:"Texas Rangers", oppPitcher:"Jacob deGrom", oppId:594798, oppXERA:3.53, oppBullpenERA:4.31, bullpenSO:41.07, runsL3:null, ops:null, opsL3:null },
    { game:"ARI @ CLE", team:"Arizona Diamondbacks", abbr:"ARI", ha:"Away", pitcher:"Kohl Drake", opp:"Cleveland Guardians", oppPitcher:"Parker Messick", oppId:800048, oppXERA:3.14, oppBullpenERA:3.71, bullpenSO:36.99, runsL3:null, ops:null, opsL3:null },
    { game:"ARI @ CLE", team:"Cleveland Guardians", abbr:"CLE", ha:"Home", pitcher:"Parker Messick", opp:"Arizona Diamondbacks", oppPitcher:"Kohl Drake", oppId:684442, oppXERA:8.53, oppBullpenERA:4.11, bullpenSO:39.75, runsL3:null, ops:null, opsL3:null },
    { game:"WSH @ ATL", team:"Washington Nationals", abbr:"WSH", ha:"Away", pitcher:"Miles Mikolas", opp:"Atlanta Braves", oppPitcher:"Reynaldo López", oppId:625643, oppXERA:4.61, oppBullpenERA:3.41, bullpenSO:36.86, runsL3:null, ops:null, opsL3:null },
    { game:"WSH @ ATL", team:"Atlanta Braves", abbr:"ATL", ha:"Home", pitcher:"Reynaldo López", opp:"Washington Nationals", oppPitcher:"Miles Mikolas", oppId:571945, oppXERA:5.2, oppBullpenERA:4.98, bullpenSO:54.81, runsL3:null, ops:null, opsL3:null },
    { game:"NYY @ CHC", team:"New York Yankees", abbr:"NYY", ha:"Away", pitcher:"Max Fried", opp:"Chicago Cubs", oppPitcher:"David Peterson", oppId:656849, oppXERA:5.13, oppBullpenERA:3.94, bullpenSO:42.25, runsL3:null, ops:null, opsL3:null },
    { game:"NYY @ CHC", team:"Chicago Cubs", abbr:"CHC", ha:"Home", pitcher:"David Peterson", opp:"New York Yankees", oppPitcher:"Max Fried", oppId:608331, oppXERA:2.51, oppBullpenERA:2.96, bullpenSO:39.95, runsL3:null, ops:null, opsL3:null },
    { game:"KC @ COL", team:"Kansas City Royals", abbr:"KC", ha:"Away", pitcher:"Luinder Avila", opp:"Colorado Rockies", oppPitcher:"Ryan Feltner", oppId:663372, oppXERA:5.85, oppBullpenERA:4.96, bullpenSO:47.07, runsL3:null, ops:null, opsL3:null },
    { game:"KC @ COL", team:"Colorado Rockies", abbr:"COL", ha:"Home", pitcher:"Ryan Feltner", opp:"Kansas City Royals", oppPitcher:"Luinder Avila", oppId:679883, oppXERA:4.83, oppBullpenERA:5.3, bullpenSO:59.52, runsL3:null, ops:null, opsL3:null },
    { game:"SF @ SD", team:"San Francisco Giants", abbr:"SF", ha:"Away", pitcher:"Tyler Mahle", opp:"San Diego Padres", oppPitcher:"Walker Buehler", oppId:621111, oppXERA:4.43, oppBullpenERA:3.61, bullpenSO:37.34, runsL3:null, ops:null, opsL3:null },
    { game:"SF @ SD", team:"San Diego Padres", abbr:"SD", ha:"Home", pitcher:"Walker Buehler", opp:"San Francisco Giants", oppPitcher:"Tyler Mahle", oppId:641816, oppXERA:4.16, oppBullpenERA:4.3, bullpenSO:55.11, runsL3:null, ops:null, opsL3:null },
    { game:"BOS @ LAD", team:"Boston Red Sox", abbr:"BOS", ha:"Away", pitcher:"Payton Tolle", opp:"Los Angeles Dodgers", oppPitcher:"Yoshinobu Yamamoto", oppId:808967, oppXERA:3.19, oppBullpenERA:4.02, bullpenSO:42.2, runsL3:null, ops:null, opsL3:null },
    { game:"BOS @ LAD", team:"Los Angeles Dodgers", abbr:"LAD", ha:"Home", pitcher:"Yoshinobu Yamamoto", opp:"Boston Red Sox", oppPitcher:"Payton Tolle", oppId:801139, oppXERA:2.91, oppBullpenERA:2.97, bullpenSO:33.42, runsL3:null, ops:null, opsL3:null },
    { game:"MIL @ LAA", team:"Milwaukee Brewers", abbr:"MIL", ha:"Away", pitcher:"Robert Gasser", opp:"Los Angeles Angels", oppPitcher:"Brent Suter", oppId:608718, oppXERA:4.22, oppBullpenERA:4.37, bullpenSO:47.1, runsL3:null, ops:null, opsL3:null },
    { game:"MIL @ LAA", team:"Los Angeles Angels", abbr:"LAA", ha:"Home", pitcher:"Brent Suter", opp:"Milwaukee Brewers", oppPitcher:"Robert Gasser", oppId:688107, oppXERA:3.74, oppBullpenERA:3.66, bullpenSO:41.78, runsL3:null, ops:null, opsL3:null },
    { game:"DET @ ATH", team:"Detroit Tigers", abbr:"DET", ha:"Away", pitcher:"Framber Valdez", opp:"Athletics", oppPitcher:"Jack Perkins", oppId:678022, oppXERA:4.05, oppBullpenERA:5.65, bullpenSO:45.12, runsL3:null, ops:null, opsL3:null },
    { game:"DET @ ATH", team:"Athletics", abbr:"ATH", ha:"Home", pitcher:"Jack Perkins", opp:"Detroit Tigers", oppPitcher:"Framber Valdez", oppId:664285, oppXERA:4.28, oppBullpenERA:3.79, bullpenSO:44.76, runsL3:null, ops:null, opsL3:null }
  ],
  runsRank: [],
  opsRank: [],
  bullpen: [["ATH", 5.65, 1.51, 199, 441, 45.12], ["KC", 5.3, 1.54, 197, 331, 59.52], ["WSH", 4.98, 1.47, 228, 416, 54.81], ["COL", 4.96, 1.49, 185, 393, 47.07], ["MIN", 4.87, 1.51, 208, 368, 56.52], ["CIN", 4.52, 1.45, 233, 379, 61.48], ["PHI", 4.47, 1.35, 148, 429, 34.5], ["PIT", 4.38, 1.42, 213, 455, 46.81], ["LAA", 4.37, 1.39, 211, 448, 47.1], ["STL", 4.33, 1.39, 191, 364, 52.47], ["TEX", 4.31, 1.34, 138, 336, 41.07], ["SF", 4.3, 1.4, 178, 323, 55.11], ["HOU", 4.13, 1.31, 197, 443, 44.47], ["ARI", 4.11, 1.23, 128, 322, 39.75], ["LAD", 4.02, 1.27, 165, 391, 42.2], ["BAL", 3.96, 1.26, 143, 363, 39.39], ["TB", 3.96, 1.19, 153, 401, 38.15], ["CHC", 3.94, 1.3, 158, 374, 42.25], ["MIA", 3.92, 1.22, 178, 419, 42.48], ["TOR", 3.84, 1.3, 177, 454, 38.99], ["NYM", 3.82, 1.24, 165, 461, 35.79], ["CHW", 3.82, 1.31, 228, 482, 47.3], ["DET", 3.79, 1.31, 171, 382, 44.76], ["CLE", 3.71, 1.31, 155, 419, 36.99], ["MIL", 3.66, 1.29, 178, 426, 41.78], ["SD", 3.61, 1.26, 177, 474, 37.34], ["SEA", 3.54, 1.27, 127, 336, 37.8], ["ATL", 3.41, 1.17, 150, 407, 36.86], ["BOS", 2.97, 1.16, 130, 389, 33.42], ["NYY", 2.96, 1.2, 149, 373, 39.95]]
};
